[alias]
bin = "espflash save-image --chip esp32c3 crimpdeq.bin"

[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip esp32c3 --no-location --preverify --restore-unwritten --always-print-stacktrace --catch-hardfault"

[env]
# Defmt Logging
DEFMT_LOG = "off" # Use "trace/debug/info/error" to enable defmt logging

# Progressor
CALIBRATION_CURVE     = "FFFFFFFFFFFFFFFF00000000"
DEVICE_ID             = "AAAAAAAAAAAA"
DEVICE_NAME           = "Progressor_7125"
DEVICE_VERSION_NUMBER = "1.1.4"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
  # Defmt support
  "-C",
  "link-arg=-Tdefmt.x",
  # Link all sections
  "-C",
  "link-arg=-Tlinkall.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
