[book]
title        = "Crimpdeq"
description  = "BLE dynamometer designed for finger training"
authors      = ["Sergio Gasquez"]
multilingual = false
language     = "en"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/SergioGasquez/crimpdeq"

